@hostAddress = http://localhost:8069

###
POST {{hostAddress}}/movies
Content-Type: application/json

{
    "title": "Spaceballs",
    "genres": [
        "Action"
    ]
}

###
@id = bfe1aa9e-70ac-42dc-bf96-123f50f3c6be
GET {{hostAddress}}/movies/{{id}}