@hostAddress = http://localhost:8069

###
# @name createMovie
POST {{hostAddress}}/movies
Content-Type: application/json

{
    "title": "Spaceballs",
    "genres": ["Comedy"]
}

###

@movieId = {{createMovie.response.body.$.id}}
GET {{hostAddress}}/movies/{{movieId}}

###
GET {{hostAddress}}/movies

###
DELETE {{hostAddress}}/movies/{{movieId}}