@hostAddress = http://localhost:8069

###
# @name createMovie
POST {{hostAddress}}/movies
Content-Type: application/json

{
    "title": "Spaceballs",
    "genres": ["Comedy"]
}

###

@movieId = {{createMovie.response.body.$.id}}
GET {{hostAddress}}/movies/{{movieId}}

###
GET {{hostAddress}}/movies

###
DELETE {{hostAddress}}/movies/{{movieId}}

###
PUT {{hostAddress}}/movies/db184ed8-8d7c-4bde-bf67-a7362bb79dec
Content-Type: application/json

{
    "title": "Spaceballs",
    "genres": ["Comedy", "Action", "ScienceFiction"]
}

###
GET {{hostAddress}}/genres

###
# @name createTheater
POST {{hostAddress}}/theaters
Content-Type: application/json

{
    "name": "01",
    "seatingArrangement": "Default"
}

###
@theaterId = {{createTheater.response.body.$.id}}
GET {{hostAddress}}/theaters/{{theaterId}}

###

GET {{hostAddress}}/theaters


###
DELETE {{hostAddress}}/theaters/{{theaterId}}

###
PUT {{hostAddress}}/theaters/{{theaterId}}
Content-Type: application/json

{
    "name": "02",
    "seatingArrangement": "Default"
}

###
POST {{hostAddress}}/showings
Content-Type: application/json

{
    "theaterId": "7864877c-c23c-4c76-bfe1-b46b1942b15a",
    "movieId": "e2042f57-c376-4443-b44a-b961dced8da8",
    "showtime": "2024-02-12T00:00"
}

###
GET {{hostAddress}}/showings