@hostAddress = http://localhost:8069

### GetShowingsEnpoint
# @name getShowings
GET {{hostAddress}}/showings

###
@getShowingsId = {{getShowings.response.body.$.[0].id}}

### GetSeats
# @name getSeats
GET {{hostAddress}}/showings/{{getShowingsId}}/seats

###
@getSeatsId = {{getSeats.response.body.$.[0].id}}

### GetSeat
GET {{hostAddress}}/showings/{{getShowingsId}}/seats/{{getSeatsId}}

### GetSeats (filtered
GET {{hostAddress}}/showings/{{getShowingsId}}/seats?occupancy=Reserved

### UpdateSeat
PATCH {{hostAddress}}/showings/{{getShowingsId}}/seats/{{getSeatsId}}
Content-Type: application/json

{
    "action": "Reserve"
}