@hostAddress = http://localhost:8069

### GetShowingsEnpoint
# @name getShowings
GET {{hostAddress}}/showings

###

@getShowingsId = {{getShowings.response.body.$.[0].id}}

### GetShowingEndpoint
# @name getShowing
GET {{hostAddress}}/showings/{{getShowingsId}}

###

@getShwoingId = {{getShowing.response.body.$.id}}

### AddShowingEndpoint
# @name addShowing
POST {{hostAddress}}/showings
Content-Type: application/json

{
    "theaterId": "7864877c-c23c-4c76-bfe1-b46b1942b15a",
    "movieId": "e2042f57-c376-4443-b44a-b961dced8da8",
    "showtime": "2024-02-12T00:00"
}

###
@addShowingId = {{addShowing.response.body.$.id}}

### UpdateShowingEndpoint
# @name updateShowing
PUT {{hostAddress}}/showings/{{addShowingId}}
Content-Type: application/json

{
    "theaterId": "7864877c-c23c-4c76-bfe1-b46b1942b15a",
    "movieId": "e2042f57-c376-4443-b44a-b961dced8da8",
    "showtime": "2024-02-13T00:00"
}

### GetShowingEndpoint
DELETE {{hostAddress}}/showings/{{addShowingId}}